"""empty message

Revision ID: 5ba6baae414c
Revises: 2e1471e6ac72
Create Date: 2025-09-18 01:09:23.552141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba6baae414c'
down_revision = '2e1471e6ac72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('otps_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('otps_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
