"""added university verification

Revision ID: c5d773ba9b0a
Revises: ba7a7a489528
Create Date: 2025-10-06 20:33:44.035303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d773ba9b0a'
down_revision = 'ba7a7a489528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tup_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['tup_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tup_id')

    # ### end Alembic commands ###
