"""personal info per student

Revision ID: dfd48bd9d51b
Revises: e9d4375bbf67
Create Date: 2025-12-02 13:49:10.901395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd48bd9d51b'
down_revision = 'e9d4375bbf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_background',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('father_occupation', sa.String(length=255), nullable=True),
    sa.Column('father_contact', sa.String(length=20), nullable=True),
    sa.Column('father_highest_education', sa.String(length=255), nullable=True),
    sa.Column('father_employer', sa.String(length=255), nullable=True),
    sa.Column('father_employer_address', sa.String(length=255), nullable=True),
    sa.Column('father_income_bracket', sa.String(length=255), nullable=True),
    sa.Column('mother_name', sa.String(length=255), nullable=True),
    sa.Column('mother_occupation', sa.String(length=255), nullable=True),
    sa.Column('mother_contact', sa.String(length=20), nullable=True),
    sa.Column('mother_highest_education', sa.String(length=255), nullable=True),
    sa.Column('mother_employer', sa.String(length=255), nullable=True),
    sa.Column('mother_employer_address', sa.String(length=255), nullable=True),
    sa.Column('mother_income_bracket', sa.String(length=255), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_occupation', sa.String(length=255), nullable=True),
    sa.Column('guardian_contact', sa.String(length=20), nullable=True),
    sa.Column('guardian_highest_education', sa.String(length=255), nullable=True),
    sa.Column('guardian_employer', sa.String(length=255), nullable=True),
    sa.Column('guardian_employer_address', sa.String(length=255), nullable=True),
    sa.Column('guardian_income_bracket', sa.String(length=255), nullable=True),
    sa.Column('number_of_siblings', sa.Integer(), nullable=True),
    sa.Column('income_bracket', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('personal_information',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('middlename', sa.String(length=80), nullable=True),
    sa.Column('extension_name', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('campus', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('course', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('facebook_link', sa.String(length=255), nullable=True),
    sa.Column('birthplace', sa.String(length=255), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('citizenship', sa.String(length=80), nullable=True),
    sa.Column('religion', sa.String(length=80), nullable=True),
    sa.Column('civil_status', sa.String(length=80), nullable=True),
    sa.Column('lrn', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_information')
    op.drop_table('family_background')
    # ### end Alembic commands ###
